# Generated by Django 5.0.6 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
    ]
