# Generated by Django 5.0.6 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0002_alter_energyforecast_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
