# Generated by Django 5.0.6 on 2024-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0003_alter_energyforecast_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
