# Generated by Django 5.0.6 on 2024-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0004_alter_energyforecast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='insight',
            field=models.TextField(max_length=2000),
        ),
    ]
