# Generated by Django 5.0.6 on 2024-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0005_alter_energyforecast_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='country',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='pestle',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='region',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='sector',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='source',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='title',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='energyforecast',
            name='topic',
            field=models.TextField(max_length=2000),
        ),
    ]
