# Generated by Django 5.0.6 on 2024-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0007_alter_energyforecast_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
