# Generated by Django 5.0.6 on 2024-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0008_alter_energyforecast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='insight',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
