# Generated by Django 5.0.6 on 2024-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0009_alter_energyforecast_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='likelihood',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
