# Generated by Django 5.0.6 on 2024-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0010_alter_energyforecast_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='likelihood',
            field=models.IntegerField(),
        ),
    ]
