# Generated by Django 5.0.6 on 2024-05-15 12:49

import Blackcoffer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0011_alter_energyforecast_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
