# Generated by Django 5.0.6 on 2024-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackcoffer_app', '0012_alter_energyforecast_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyforecast',
            name='end_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
